default: &default
  adapter: postgresql
  encoding: unicode
  pool: 15

development:
  <<: *default
  database: rails-api-template_development
  username: wiskyly
  password: 123456

test:
  <<: *default
  database: rails-api-template_test
  username: wiskyly
  password: 123456

production:
  <<: *default
  database: rails-api-template_production
  username: <%= ENV['PG_USERNAME'] %>
  password: <%= ENV['PG_PASSWORD'] %>
 